name: enforcing branch protection

on:
  push:
  workflow_dispatch:

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and run unit test
        uses: actions/checkout@v3
      
      - name: installing reqs and run
        run: | 
              pip install -r requirements.txt
              python3 scripts/branch_protec.py