name: adding and reading in a secret
on: [push]

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: reading a secret
        env: 
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN
